### ISSUE TITLE
Unable to use the `dynamic` keyword

### ISSUE THREAD

**Issue by nesteruk** [scriptcs/scriptcs#1057]
Scriptcs is complaining that the `dynamic` keyword is not supported :(

**Comment by khellang** [comment]
Yeah, the Roslyn bits we use CTP Sept. 2012 doesn't support `dynamic` and `async`/`await`, and we're unable to use newer bits because the scripting APIs were temporarily removed.

If you need to use these features, you could try running with the Mono module, using `scriptcs -modules mono`.

We are working with Microsoft to get up on the newer Roslyn scripting bits, but it's still a bit early for it. You can check out the progress at https://github.com/scriptcs/scriptcs-engines

**Comment by denfromufa** [comment]
https://github.com/scriptcs/scriptcs/issues/1092

**Comment by adamralph** [comment]
Closed by https://github.com/scriptcs/scriptcs/pull/1064
