### ISSUE TITLE
Publish scriptcs.exe as its own nuget package

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#1061]
Per chatting with @stankovski, it would be useful to publish scriptcs.exe as its own NuGet package, thus allowing automation scripts to easily install and run the exe from a local bin folder.

---

Depends on https://github.com/scriptcs/scriptcs/pull/1064

**Comment by adamralph** [comment]
:+1: the exe should sit inside /tools

**Comment by glennblock** [comment]
Will the MSBuild target automatically do that if it sees an exe? I am working on this PR now, and was modifying our Build.proj and adding a new <NuGetProjects> entry.

**Comment by glennblock** [comment]
I'll shortly find out I guess..I am testing :-)

**Comment by glennblock** [comment]
@adamralph yep, it puts it in tools, perfect!

**Comment by stankovski** [comment]
Great! Thanks a lot guys.

**Comment by adamralph** [comment]
@glennblock it's going into tools because that's what nuspec is telling it to do, see https://github.com/scriptcs/scriptcs/blob/a4bbfb38dbb60db1709db1bd932f27fd2d2bd2bc/src/ScriptCs/Properties/scriptcs.nuspec

It should be noted that this is the nuspec which is designed to create the Chocolatey package. This has a couple of consequences:

* It takes a dependency on NuGet.CommandLine
* It includes a chocolateyInstall.ps1

The presence of chocolateyInstall.ps1, whilst a little ugly, isn't really much of an issue. It would be nice to remove it though.

IMO the NuGet.CommandLine dependency needs to be removed from the NuGet package. It doesn't actually break anything, but it's completely inappropriate and it just feels too odd to ship the package with this dependency. Moreover, I'm wondering if the NuGet.CommandLine dependency is even necessary for the Chocolatey package.

Which brings me to another point. Our Chocolatey package has been shipping with the Roslyn.Compilers.* assemblies baked in for some time now. AFAIK this is a (accidental?) license violation and the original design was that we download the Roslyn.Compilers.* separately during installation using nuget.exe, hence the dependency on NuGet.CommandLine. I'm not sure if this still happens or not. Perhaps it does, and overwrites the Roslyn.Compilers.* which we are shipping in our package.

So the question remains, do we embrace the license violation (is it still a violation?) and just drop the dependency on NuGet.CommandLine (and simplify chocolateyInstall.ps1), or do we pull the Roslyn.Compilers.* assemblies out of our Chocolatey package and ensure the explicit download of them during installation works?

If the former, we solve the problem for our NuGet package at the same time. If the latter, we'll have to solve the same problem for our NuGet package by including an Install.ps1 to explicitly download the Roslyn.Compilers.* packages and extract the assemblies when our NuGet package is installed.

Given that we are hoping to move to the new Roslyn fairly soon, I vote for the former option. We remove the dep on NuGet.CommandLine in our chocolatey package, simplify chocolateyInstall.ps1 and continue to bake in the Roslyn.Compilers.* in our package.

**Comment by glennblock** [comment]
Yeah I noticed the chocolatey install. The problem with relying on the
installation script is that it will not work cross platform.

However, I would vote a third option. We only put scriptcs.exe in the new
package and make it depend on scriptcs.hosting etc. When the package is
installed it will pull all its dependencies which will all end up in the
bin.

**Comment by adamralph** [comment]
I'm not sure it will work that way. AFAIK a tools exe in a NuGet package needs to ship with all it's assemblies present in the tools folder next to it. Nuget will see the dependency, but all that it will do is install the dependent nuget package. I'm fairly sure it won't reach into the nuget packages for the DLLs and copy them across into the tools directory of the exe.

**Comment by adamralph** [comment]
Note that a tools package is not installed into any project. It's a solution level package that just allows build scripts etc. to use the exe.

**Comment by glennblock** [comment]
I see. Well the request here is for xPlat and command line execution.

So perhaps it should not be in tools and should be a standard package.

**Comment by adamralph** [comment]
In that case the NuGet client will insist on it being installed into a project, and that project will end up with references to scriptcs.exe and all the dependencies (19 in total). This would all be pulled into the output folder of that project when it is built, and the automation script would have to reach in there for the exe, rather than running it from the packages folder. When shipping the app/library, care would have to be taken to strip out all the redundant artifacts that result from having the scriptcs.exe reference.

The tools folder is the right solution. It's designed for exactly this scenario (automation scripts). The only stumbling block in our case is the restrictive license which prevents us (theoretically at least :wink: ) from forming the package in a natural manner, with the Roslyn assemblies sitting next to the exe.

Another idea I had a while back is to hook into assembly resolution (which we already do for other purposes) and download the assemblies on the fly during first execution. It's a bit left field but it would work. It would require an internet connection and NuGet to be up during first execution, but that's like to occur just after installation anyway.

**Comment by glennblock** [comment]
We need a solution here. It sounds like solution-level projects in the traditional senses are going away anyway in NuGet

**Comment by adamralph** [comment]
@glennblock solution level packages are indeed going away, but only when using project.json.

IMHO this is a massive fail and will render a huge number of packages unusable when using project.json.

**Comment by glennblock** [comment]
Anyway, let's put our heads together and figure out if we can come up with
some reasonable way to ship scriptcs.exe as a package and WITHOUT requiring
powershell scripts.

One idea I was thinking of was to have a package that contains a dll such
that the first time it is loaded, it copies the exe or something. The exe
could even have a diff name and be sitting in the content folder so VS
doesn't pick it up.

**Comment by adamralph** [comment]
At the moment, I don't see anyway to do this in project.json.

With the traditional packages.config mechanism, it's trivial, apart from the issue of the Roslyn CTP license. But perhaps that problem will simply vanish when we move to the latest Roslyn? Does is have a more permissive license?

**Comment by filipw** [comment]
Yes it's MIT.

**Comment by adamralph** [comment]
Cool, so for traditional NuGet, this is trivial, just put in the tools folder and package it up.

**Comment by glennblock** [comment]
Aah right we went with our own binaries. So just merge
accept my PR, it already does this ;-)

**Comment by adamralph** [comment]
@glennblock see https://github.com/scriptcs/scriptcs/issues/1061#issuecomment-118159535

> It should be noted that this is the nuspec which is designed to create the Chocolatey package. This has a couple of consequences:
> 
> * It takes a dependency on NuGet.CommandLine
> * It includes a chocolateyInstall.ps1
> 
> The presence of chocolateyInstall.ps1, whilst a little ugly, isn't really much of an issue. It would be nice to remove it though.
> 
> IMO the NuGet.CommandLine dependency needs to be removed from the NuGet package. It doesn't actually break anything, but it's completely inappropriate and it just feels too odd to ship the package with this dependency. Moreover, I'm wondering if the NuGet.CommandLine dependency is even necessary for the Chocolatey package.

I think we need a new nuspec which create a separate package specifically crafted for NuGet.

**Comment by glennblock** [comment]
That is what my PR contains.

**Comment by glennblock** [comment]
Aah gotcha

**Comment by adamralph** [comment]
@glennblock are you referring to https://github.com/scriptcs/scriptcs/pull/1062 ? It doesn't contain a new nuspec. It uses the current nuspec designed for Chocolatey.

In fact, the `BuildChocolateyPackage` MSBuild target is currently overwriting the package created by the `BuildNuGetPackages` target because they have the same name.

Also, `BuildNuGetPackages` packages against the csproj and not the nuspec, so the resulting nupkg is unusable anyway. I.e. it contains `lib/net45/scriptcs.exe` and `content/Properties/icon.ico`. We need a specially crafted nuspec to produce scriptcs.nukpg for NuGet with everything in `tools/` and no dep on NuGet.CommandLine. We also need to output the Chocolatey package to a separate folder to stop it overwriting the NuGet package. On top of that we also need work on the build server to publish everything to the right place, including thinking about how to use MyGet, since we will have the same overwriting problem there.

Anyway, this is all a no-go until we've upgraded to the latest Roslyn.

**Comment by adamralph** [comment]
Sorry, I overlapped with

> Aah gotcha

**Comment by glennblock** [comment]
We should decide if we're going to ado anything with this.

**Comment by pawelpabich** [comment]
Hi,

Has there been any decision made?

**Comment by glennblock** [comment]
@pawelpabich @stankovski finally merged this. Should be released shortly
