### ISSUE TITLE
Allow Unit Testing of Scripts with NUnit

### ISSUE THREAD

**Issue by pbgodwin** [scriptcs/scriptcs#115]
This was an idea I had while sitting around yesterday and haven't quite had a chance to play with yet, but I figured I'd open a discussion here to see what people think. There are already a great amount of test frameworks for use with C#, and I figured it'd be a great idea to leverage those in some way for testing scripts written for scriptcs.

The idea was to expose an interface (something along the lines of ITestEngine) that dictates how a certain test framework's test runner is supposed to handle tests in scriptcs. Depending on where we go with #87, I figure that if scriptcs CLI were passed a -test or -runTests flag, it could build the scripts, then build all of the csx files in a "test" directory, passing that binary into the test framework. I think this kind of model could possibly allow us to distribute the test engines as packages via NuGet [ much like they already are ], and allow developers to build and test however they need.

I know I should have thrown together an example, simply because code speaks better than I can, but I wanted to see people's ideas before I dove head first into this. Thoughts? Suggestions?

**Comment by jchannon** [comment]
Just came across this after discussing a plan with the team.

We are looking to create a set of integration tests for our API with ScriptCs but would like to have a runner that can execute a bunch of our scripts.

Where are we with xUnit support?

**Comment by adamralph** [comment]
@jchannon AFAIK nothing has happened since. I've turned this task into NUnit only. Given that xunit 2.0 is out, it would be interesting to see if we can knock together something to allow this.

**Comment by jchannon** [comment]
Yup that's what I was thinking :)

**Comment by filipw** [comment]
nunit :heart:  

:trollface:

**Comment by glennblock** [comment]
i was planning to work in this and started, but it got stagnated due to
personal issues.

**Comment by jchannon** [comment]
I've created an empty repo with the idea of writing a script library for xUnit to see if its even possible.

Happy to give anyone interested commit access  (HINT HINT, NUDGE NUDGE!!!)

https://github.com/VQComms/ScriptCs.xUnit

**Comment by filipw** [comment]
unless you have to, use normal script packs as then you will get language services

**Comment by jchannon** [comment]
noted. thanks. do you want commit access? :wink:

**Comment by filipw** [comment]
why not, though last time I looked at it was not possible :)

**Comment by jchannon** [comment]
:cry: I was hoping xunit v2 might open it up a bit more

access given :smile:

**Comment by jchannon** [comment]
Might be worth a look here https://github.com/xunit/xamarinstudio.xunit

This is a Xamarin Studio xUnit runner that discovers tests and runs them......

https://github.com/xunit/xamarinstudio.xunit

**Comment by glennblock** [comment]
I already had created one ;-) go for it though

Here is a bunch of detail Brad Wilson gave me. You may want to join the
slack room.

xUnit

Discovery is already always based on `IAssemblyInfo` because it's designed
to work without binaries in place, so really it's just the running bit
that's complicated.

bradwilson[11:30 AM]If you look at Xunit2:
https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Frameworks/v2/Xunit2.cs

GitHub
xunit/xunit
xunit - xUnit.net is a free, open source, community-focused unit testing
tool for the .NET Framework.

bradwilson[11:31 AM]We could presumably add a constructor there eventually
which takes just `AssemblyName`.

bradwilson[11:31 AM]That would allow you to use an already-created assembly.

bradwilson[11:32 AM]But for now, your best bet (as I alluded to on Twitter)
is to just link against the execution library directly, and instantiate
`XunitTestFramework`.
https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/XunitTestFramework.cs

bradwilson[11:33 AM]This will give you access to create the discoverer with
the `IAssemblyInfo` (taken from `Reflector.Wrap`) and the executor with
`AssemblyName`, both of which you should have already at your disposal.

bradwilson[11:34 AM]The process is fairly simple, then: create a visitor to
collect the test cases that you get from discovery, and then send those
test cases into the executor to be run.

bradwilson[11:34 AM]`TestDiscoveryVisitor` is useful for the former:
https://github.com/xunit/xunit/blob/master/src/common/TestDiscoveryVisitor.cs

bradwilson[11:35 AM]Everything is based on messages. The calls to initiate
discovery and execution take the visitors, which give you messages back
related to discovery and execution progress.

bradwilson[11:36 AM]Looking at a runner like the Console runner or the
MSBuild runner should give you a pretty good idea how it works

bradwilson[11:36 AM]You'll just be directly calling into the discoverer and
executor rather than using the stuff in `xunit.runner.utility` like they do.


https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.testadapter/VsTestRunner.cs

**Comment by jchannon** [comment]
Ah we can work off your repo :)

**Comment by glennblock** [comment]
It's empty, but it is in scriptcs-contrib. :-)

https://github.com/scriptcs-contrib/scriptcs-xunit

I will add you and you can take it and do what you will.

**Comment by glennblock** [comment]
I added you to our contrib org. Welcome!

**Comment by glennblock** [comment]
@jchannon read the notes I gave you, they may help.

**Comment by jchannon** [comment]
Thanks!!

The more the merrier so jump in..........pleeeeease :)
