### ISSUE TITLE
question: scriptcs_bin

### ISSUE THREAD

**Issue by awb99** [scriptcs/scriptcs#1160]
Why does Scriptcs copy the private bin files to scriptcs_bin ?

**Comment by glennblock** [comment]
scriptcs_ folders are there to avoid conflicts with existing folders in
cases where scriptcs is used within an existing solution folder. The
copying to scriptcs_bin is a migration that we do automatically if we see
bin and no scriptcs_bin. In the past keeping everything in bin caused
conflicts due to conflicting dependencies between the script and the outer
app.

**Comment by awb99** [comment]
@glennblock Thanks!
