### ISSUE TITLE
KeyNotFoundException in ScriptPackManager

### ISSUE THREAD

**Issue by agc93** [scriptcs/scriptcs#1170]
I wanted to author a new script pack, but now can't even get the simplest example working. I have uploaded a minimal example in [this repository](https://github.com/agc93/scriptcs-error/settings). the output I get from running `scriptcs .\test.csx -logLevel debug` is in [this gist](https://gist.github.com/agc93/d19a781f62079f605b4f891fce2b98cf). The main exception is:

```
ERROR: [ScriptCs.Command.ExecuteScriptCommand] Script execution failed. [System.Collections.Generic.KeyNotFoundException] The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ScriptCs.ScriptPackManager.Get[TContext]()
   at Submission#0..ctor(Object[] submissionArray, Object& submissionResult)
   at Submission#0.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmission(Func`2 submissionRunner)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at ScriptCs.Engine.Roslyn.CSharpScriptEngine.GetScriptState(String code, Object globals)
   at ScriptCs.Engine.Roslyn.CommonScriptEngine.Execute(String code, Object globals, SessionState`1 sessionState)
DEBUG: [ScriptCs.ScriptExecutor] Terminating packs
```

Let me know if you need more info

---

scriptcs: 0.16.1 installed from Chocolatey
Environment: Windows 10 (with VS2015U3 installed)

**Comment by agc93** [comment]
Are there any further debugging steps I can take here? I can't work out anyway around the problematic `ScriptPackManager` code, especially not without losing half the capabilities of a script pack.

Happy to help debug this, but without knowing scriptcs's internals, I'm not sure what the next steps are supposed to be?

**Comment by glennblock** [comment]
I wil take a look today.

**Comment by glennblock** [comment]
I think I see the issue. You are trying to Require the script pack, but it was not really registered. Thus the error that you are getting is because it could not find the script pack that you asked for i.e. `Require` used the type `TestPack` as the key and it found nothing. Granted we need a better message. 

Script Packs are discovered by being loaded from the `scriptcs_packages` folder. This is why your code is not working. You are using a `#r` to load the assembly, but that does not make it get picked up as a script pack.

To test out, what you can do is create a bin folder underneath your script, and drop your script pack binary there. I believe we will load it automatically if you do.

**Comment by glennblock** [comment]
I'll leave this bug open as we do need a better exception message.

**Comment by glennblock** [comment]
You can read about the bin folder copying approach here: https://blog.martindoms.com/2013/05/14/building-scriptcs-script-pack
