### ISSUE TITLE
Issue with ScriptPack and System.Data.SQLite and LoadExtension

### ISSUE THREAD

**Issue by donnyv** [scriptcs/scriptcs#1234]
I created a ScriptPack which references System.Data.SQLite. This part works great.
I have a dynamic link extension I'm trying to load into SQLite using LoadExtension("mod_spatialite"). 
The way this works is that "mod_spatialite.dll" and its supported files just need to live in the same folder as System.Data.SQLite for it to load correctly.
Which I have successfully tested separately in a console app. 

Right now my folder structure looks like this.

c:\gis
-- scriptcs_bin
-- test.csx

Inside "scriptcs_bin" folder I have the compiled ScriptPack with all the dll's and supporting files for "mod_spatialite". When I run test.csx it complains that the sqlite extension can't be found. But if I copy mod_spatialite.dll and its supported files to c:\gis. It runs fine. 

To me this seems like a path issue but not sure where ScriptCS is actually running the script. I tried adding "scriptcs_bin\mod_spatialite" to LoadExtension() but it still didn't find it.

Can anyone maybe point me in the right direction?
Thanks!

references
--------------------------------------------
https://sqlite.org/loadext.html
https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki
http://stackoverflow.com/questions/22667981/getting-a-working-spatialite-sqlite-system-for-x64-c-sharp

**Comment by glennblock** [comment]
Hi Donny, I'll take a look at this later today. Sorry for the delay.

**Comment by glennblock** [comment]
Sorry, I got side tracked on this.

Can you send me a link to a repo that has your script pack and your test.csx, so I can reproduce?

Thanks!

**Comment by donnyv** [comment]
I'm going to email you a zip file and instructions. Not so good with Github yet.

**Comment by glennblock** [comment]
No problem!

**Comment by glennblock** [comment]
I have a solution here and it turns out to be quite simple. In your script you set `Environment.CurrentDirectory` to the scriptcs_bin before you create the SQLite connection (it must happen then). This way that dir inherits that directly into its environment when SQLite loads the extension. I tested this and it works. You can see a gist of the code I used [here](https://gist.github.com/glennblock/3c9e36d8da42c16d1add6723b6fe05a4). You'll notice before the connection is created, I am saving the current dir and then changing it to scriptcs_bin. Then I change back after the connection is created.

The script also contains all the code from your script pack because I wanted to see if you could handle your script pack use case as a Script Library, and this proves you can.

**Comment by glennblock** [comment]
Below is a screenshot of the code running successfully.

![screen shot 2017-04-17 at 9 16 38 pm](https://cloud.githubusercontent.com/assets/141124/25114714/8e1908d4-23b5-11e7-8e99-9825db27a97b.png)

**Comment by donnyv** [comment]
Sweeeeeeeeet!! 
Simple answer to a not simple problem.
Thanks for working through this problem.

**Comment by glennblock** [comment]
👍

Sometimes you just need to take a break and the answer just comes to you :-)
