### ISSUE TITLE
Mono REPL multiline

### ISSUE THREAD

**Issue by filipw** [scriptcs/scriptcs#665]
Add multiline support for mono REPL
Currently the REPL for mono is single line only

I have a working spike but it needs some work. Unfortunately looks like the approach from Roslyn with catching compiler error might not be that simple to rebuild there.

---

**Edit by @adamralph**

This feature supports everything apart from loose functions. That has been spun off into https://github.com/scriptcs/scriptcs/issues/906

**Comment by matthewblott** [comment]
Just started using this on OSX and noticed this issue - it looks pretty old so I'm guessing this isn't being worked on?

**Comment by adamralph** [comment]
@matthewblott any Mono related work has indeed slipped down the order of importance somewhat. This is largely due to the fact that Microsoft seem committed to x-plat with their latest bits, so the hope is that, in the not too distant future, we will have a build of Roslyn that its fully x-plat and has the scripting API's reintroduced, which would allow us to kill the scriptcs Mono engine. Of course, we don't know when or indeed if that will definitely happen, so I guess Mono related scriptcs work is a little in limbo right now.

**Comment by filipw** [comment]
mono REPL multiline was fixed long time ago by @ztone in this PR #771 
however we have done a terrible job managing those and as a result things have kinda slipped away.

@ztone we discussed extracting mono multiline REPL into a single PR a while ago - can this be PR-ed separately or is it relying on the changes introduced in #771? If that's the case, let's rebase and merge it ASAP. Very sorry it was left hanging for so long

**Comment by ztone** [comment]
@filipw @adamralph @matthewblott  Tbh I would not want to merge #771 unless we really need to.  Only thing it fixes is the block parsing issue no one has actually complained about (yet!). Regarding issue #713, which #771 fixes as well, will be fixed when we get a new Mono.CSharp release because I found the issue in the mono compiler a few months ago.

So, getting back to this issue.  Adding multi-line support for everything but loose function is really easy (only 3 lines of code) as it is already supported by Mono.CSharp.  However, multi-line support for loose function will require some work.  So do we want to split this into 2 PRs or wait for a full fix?

**Comment by adamralph** [comment]
@ztone thanks for the info!

I would prefer splitting it up. If you can send a separate PR now for 'multi-line support for everything but loose functions' then we can get that in now and perhaps even make it part of 0.13. The loose function support can come later and we can spin off a separate issue for it.

**Comment by adamralph** [comment]
Fixed in #771

**Comment by ztone** [comment]
@adamralph Ehh ...sorry this is not fixed by #771. Just will be easier to implement.  Can you re-open!

**Comment by adamralph** [comment]
OK. Will your fix excluded loose functions? I.e. should we still have that spun off into a separate issue?

**Comment by ztone** [comment]
Yeah, keep it for now

**Comment by glennblock** [comment]
@ztone what's the status of this?

**Comment by ztone** [comment]
@glennblock I had almost finished the work for #664 a few months ago! I didn't push it in because something was bothering me and I needed to sleep on it.  I think I've slept on it enough now :smile: ... anyway when #664 is done this one should be a breeze.

**Comment by filipw** [comment]
fixed by https://github.com/scriptcs/scriptcs/pull/1216
