### ISSUE TITLE
ScriptCs fails to install

### ISSUE THREAD

**Issue by grishin** [scriptcs/scriptcs#901]
![image](https://cloud.githubusercontent.com/assets/3284017/5700382/6fb36436-9a4e-11e4-9baa-3988c67a9635.png)

**Comment by adamralph** [comment]
Hi @grishin, I don't think this has anything to do with the cyrillic characters in your username. I spun up a VM with the same username as you are using and the installation worked perfectly:

![image](https://cloud.githubusercontent.com/assets/677704/5700861/5026854e-9a44-11e4-8393-6114f7968f36.png)

I think the problem is that you've somehow gotten your Chocolatey and/or NuGet.CommandLine installation into a bad state. This line is telling:

![image](https://cloud.githubusercontent.com/assets/677704/5700878/881ee6da-9a44-11e4-9535-0f8616d8f8fa.png)

I would investigate reinstalling Chocolatey and/or NuGet.CommandLine and then trying again.

**Comment by grishin** [comment]
Hi @adamralph, Thank you very much for your help. We had this problem on several developer machines only on those with cyrillic usernames. We did fresh reinstall of chocolatey on each and everything is fine now! Might be some bug in version we had. Thank you very much and sorry for not checking this before posting.

**Comment by adamralph** [comment]
@grishin no problem. Glad to be of help!
