### ISSUE TITLE
Packages.config "namespace name could not be foudn"

### ISSUE THREAD

**Issue by lukaspj** [scriptcs/scriptcs#910]
Running this:

```
E:\GitHub\SparetimeTeachingMyoProject\ScriptCS [master +1 ~0 -0 !]> scriptcs -in
stall
Installing packages...
Installation completed successfully.
Saving packages in packages.config...
Updating packages.config...
Skipped SharpDX because it already exists.
Skipped SharpDX.D3DCompiler because it already exists.
Skipped SharpDX.Direct3D11 because it already exists.
Skipped SharpDX.DXGI because it already exists.
Successfully updated packages.config.
E:\GitHub\SparetimeTeachingMyoProject\ScriptCS [master +1 ~0 -0 !]> scriptcs Tri
Test.csx
ERROR: error CS0246: The type or namespace name 'SharpDX' could not be found (ar
e you missing a using directive or an assembly reference?)
```
With the following packages.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="SharpDX" version="2.6.3" targetFramework="net40" />
  <package id="SharpDX.D3DCompiler" version="2.6.3" targetFramework="net40" />
  <package id="SharpDX.Direct3D11" version="2.6.3" targetFramework="net40" />
  <package id="SharpDX.DXGI" version="2.6.3" targetFramework="net40" />
</packages>
```

And script:
```c#
using SharpDX;
```

Am I missing something? According to documentation, it should "just work" without me having to reference anything right?

Moving the dll into a subfolder and changing the script to:
```c#
#r "SharpDX/SharpDX.dll"
using SharpDX;
```

Works fine.

**Comment by adamralph** [comment]
Hi @lukaspj, thanks for raising this.

Upon investigation, the SharpDX NuGet packages look rather non-standard. It seems that all the assemblies are in a Bin folder and the package relies on an Install.ps1 script to put things in place during installation:

![image](https://cloud.githubusercontent.com/assets/677704/5997252/093bb156-aab9-11e4-8821-3c2a9039f2bc.png)

Install.ps1 is not supported by scriptcs since a) it is dependent on Visual Studio and b) it is not cross platform.

I'm afraid a manual reference using `#r` is going to be necessary for these packages. It should be necessary to move them from where they are. You should be able to reference them directly from the packages folder, e.g.`#r scriptcs_packages\SharpDX.2.6.3\Bin\DirectX11-net40\SharpDX.dll`.

**Comment by adamralph** [comment]
@lukaspj I'm closing this because I believe I've answered the question. If you still need any more information please feel free to re-open.
