### ISSUE TITLE
Script pack usings don't appear in :usings

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#992]
```batch
mkdir bug-repro
cd bug-repro
scriptcs -install ScriptCs.Nancy
scriptcs
```

```csharp
var n = Require<NancyPack>();
class TestModule: NancyModule { } // prove that the Nancy namespace is available
:usings
```

```json
[
  "System",
  "System.Collections.Generic",
  "System.Linq",
  "System.Text",
  "System.Threading.Tasks",
  "System.IO",
  "System.Net.Http"
]
```

**Comment by filipw** [comment]
this is tricky because REPL commands operate against REPL while the script packs are unwrapped at the engine level. So the Executor never knows anything about the script pack namespaces.

There is no perfect way to handle this:
 - force engine to expose namespaces (ugly and troublesome)
 - notify executor back about namespaces (so a two way communication between executor and engine, also ugly)
 - lift script pack evaluation up to the executor level (not sure how much repercussions this will have but a significant change)

**Comment by filipw** [comment]
oh scratch that I have an idea

**Comment by filipw** [comment]
I forgot the script pack session is there :)
